GAME_FPS = 60

GAME_SOUND = 0.5

SCREEN_SIZE = (900, 800)

monster_initial_health = 10
monster_health_scale_value = 1.05
last_monster_health = 0

monster_initial_gold_reward = 1
monster_initial_gold_reward_scale = 1.05
last_monster_gold_reward = 0

MENU_OVERLAY_WIDTH = 350
MENU_OVERLAY_HEIGHT = 600
MENU_OVERLAY_COLOR = (0, 0, 0, 100)
MENU_OVERLAY_POSITION = (0, 200)
MENU_OVERLAY_BORDER_RADIUS = 15

MENU_DAMAGE_TEXT_ID = 1
MENU_COMPANION_TEXT_ID = 2
MENU_COMPANION_LEVEL_TEXT_ID = 3

MENU_INCREASE_DAMAGE_TEXT = "Increase click damage X"
MENU_INCREASE_DAMAGE_TEXT_POSITION = (0, 260)
MENU_INCREASE_DAMAGE_TEXT_COLOR = (255, 255, 255)
MENU_INCREASE_DAMAGE_TEXT_FONT = "Georgia"
MENU_INCREASE_DAMAGE_TEXT_FONT_SIZE = 20

MENU_COMPANION_TEXT = "Buy companion"
MENU_COMPANION_UPGRADE_TEXT = "Companion update"
MENU_COMPANION_TEXT_POSITION = (0, 460)
MENU_COMPANION_TEXT_COLOR = (255, 255, 255)
MENU_COMPANION_TEXT_FONT = "Georgia"
MENU_COMPANION_TEXT_FONT_SIZE = 20

MENU_COMPANION_LEVEL_TEXT = "Companion Level: "
MENU_COMPANION_LEVEL_TEXT_POSITION = (0, 700)
MENU_COMPANION_LEVEL_TEXT_COLOR = (255, 255, 255)
MENU_COMPANION_LEVEL_TEXT_FONT = "Georgia"
MENU_COMPANION_LEVEL_TEXT_FONT_SIZE = 27